from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ROOT(object):
    def setupUi(self, ROOT):
        ROOT.setObjectName("ROOT")
        ROOT.resize(460, 192)
        self.centralwidget = QtWidgets.QWidget(ROOT)
        self.centralwidget.setObjectName("centralwidget")
        self.m_key = QtWidgets.QLineEdit(self.centralwidget)
        self.m_key.setGeometry(QtCore.QRect(110, 38, 181, 25))
        self.m_key.setObjectName("m_key")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(6, 110, 91, 20))
        self.label_2.setObjectName("label_2")
        self.userpermit = QtWidgets.QLineEdit(self.centralwidget)
        self.userpermit.setGeometry(QtCore.QRect(110, 110, 261, 25))
        self.userpermit.setObjectName("userpermit")
        self.create = QtWidgets.QPushButton(self.centralwidget)
        self.create.setGeometry(QtCore.QRect(110, 150, 89, 25))
        self.create.setObjectName("create")
        self.hw_id = QtWidgets.QLineEdit(self.centralwidget)
        self.hw_id.setGeometry(QtCore.QRect(110, 68, 181, 25))
        self.hw_id.setObjectName("hw_id")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.label_6.setObjectName("label_6")
        self.m_id = QtWidgets.QLineEdit(self.centralwidget)
        self.m_id.setGeometry(QtCore.QRect(110, 7, 181, 25))
        self.m_id.setObjectName("m_id")
        self.create_2 = QtWidgets.QPushButton(self.centralwidget)
        self.create_2.setGeometry(QtCore.QRect(270, 150, 89, 25))
        self.create_2.setObjectName("create_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 70, 71, 25))
        self.pushButton.setObjectName("pushButton")
        self.size_user_permit = QtWidgets.QLCDNumber(self.centralwidget)
        self.size_user_permit.setGeometry(QtCore.QRect(380, 110, 64, 23))
        self.size_user_permit.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.size_user_permit.setObjectName("size_user_permit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 90, 67, 17))
        self.label_4.setObjectName("label_4")
        ROOT.setCentralWidget(self.centralwidget)

        self.retranslateUi(ROOT)
        QtCore.QMetaObject.connectSlotsByName(ROOT)

    def retranslateUi(self, ROOT):
        _translate = QtCore.QCoreApplication.translate
        ROOT.setWindowTitle(_translate("ROOT", "USERPERMIT_CREATOR"))
        self.m_key.setText(_translate("ROOT", "10121"))
        self.label.setText(_translate("ROOT", "M_KEY"))
        self.label_2.setText(_translate("ROOT", "USERPERMIT"))
        self.create.setText(_translate("ROOT", "Create"))
        self.hw_id.setText(_translate("ROOT", "12345"))
        self.label_3.setText(_translate("ROOT", "HW_ID"))
        self.label_6.setText(_translate("ROOT", "M_ID"))
        self.m_id.setText(_translate("ROOT", "10"))
        self.create_2.setText(_translate("ROOT", "Save to File"))
        self.pushButton.setText(_translate("ROOT", "Create"))
        self.label_4.setText(_translate("ROOT", "Размер"))


